version: '3.7'

services:

  db:
    image: postgres:14.9-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db # Environmental variables file for Postgres database service
    network_mode: "host"

  chromia:
    user: "${UID}:${GID}" # Arguemnts passed from command line about user and group ID
    image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.14.3
    network_mode: "host" # To be able to use locahost network to connect to postgres database service ('db')
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  postgres_data:
